FROM python:3.11.10 AS builder

WORKDIR /app
# 安装构建依赖

COPY requirements-rerank.txt .

RUN pip install  -r requirements-rerank.txt

COPY retrival_server_octen_.py .

EXPOSE 8889

HEALTHCHECK --interval=30s --timeout=10s --start-period=120s --retries=3 \
    CMD curl -f http://localhost:8889/health || exit 1

CMD ["python", "retrival_server_octen_.py"]
